<template>
  <view-box body-padding-top="0px" body-padding-bottom="0px" class="cehui">
    <tianditu @mapload="mapload"
              @cehuiClick="cehuiClick"
              :loading=true
              ref="map" mapid="cehuimap" style="height:100%;"></tianditu>
    <!-- 固定底部 -->
    <div class="cehui-bottom">
      <div class="bitem" v-for="(i,idx) in navData" style="border-right:1px solid #eee;">
        <div class="bitem-tit" @click="dataShow(i)" :class="{'on':i.show}">{{i.name}}</div>
        <div class="bitem-list" v-if="i.show"  style="overflow: scroll;" :style="{'height':idx==0?'auto':'300px'}">
          <a @click="cehuiLoad(ii)" v-for="ii in i.list" :class="{'on':ii.url==nowurl}" style="font-size: 10px;">{{ii.name}}</a>
        </div>
      </div>
    </div>
    <!-- 固定头部介绍 -->
    <div v-if="nowname" style="position: fixed;top:10px;width:calc(100% - 20px);left:10px;background: #fff;border-radius: 5px;padding: 10px;box-sizing: border-box">
      <div style="font-size: 16px;font-weight: bold;">{{nowname}}</div>
      <div>{{nowstr}}</div>
    </div>
    <!-- 内容弹出 -->
    <popup height="calc(100% - 200px)"
           v-model="content.show"
           style="width:calc(100% - 40px);"
           :show-mask="false" class="cehui-con">
      <div class="info-pop-tool" style="width:calc(100% - 20px);">
        <img src="@/images/down10.png" @click="content.show=false" alt="">
      </div>
      <!--内容-->
      <div class="con-list" style="overflow-y:scroll;overflow-x:hidden;height:calc(100% );">
        <tab v-if="nowtab && nowtab.length>0">
          <tab-item v-for="(i,idx) in nowtab" :selected="idx==tabidx" @on-item-click="tabidx=idx">{{i.name}}</tab-item>
        </tab>
        <div v-if="nowtab && nowtab.length>0">
          <div class="con-item" v-for="i in nowtab[tabidx].field">
            <div>{{i}}:</div>
            <div>{{content.data[i]}}</div>
          </div>
        </div>
      </div>
    </popup>

  </view-box>
</template>
<script>
  import Util from '@/libs/util';
  import esriLoader from 'esri-loader'
  import {ViewBox,Popup,Tab,TabItem} from 'vux';
  import Tianditu from '@/components/libs/tianditu/main';
  export default {
    components:{
      ViewBox,Tianditu,Popup,Tab,TabItem
    },
    data(){
      return {
        nowurl:"",
        nowname:"",
        nowstr:"",
        nowtab:[],
        tabidx:0,
        navData:[
          {
            name:'地形图',
            show:false,
            list:[
              {
                name:'1:500',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/DiXingT/MapServer/0',
                str:"温州三区，温州2000坐标系，2011年温州城市坐标系转温州2000坐标系，2016年更新测绘数据。",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','测区名称','测区代码','所有权单位名称','生产单位名称','密级','参照图式','大地基准','高程基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始测绘时间','更新时间','最新更新时间','比例尺分母','图幅等高距','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'1:2000',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/DiXingT/MapServer/1',
                str:"鹿城、龙湾、瓯海三区范围，覆盖面积约1166平方公里，共计图幅1166幅。2014年测制。",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','测区名称','测区代码','所有权单位名称','生产单位名称','密级','参照图式','大地基准','高程基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始测绘时间','更新时间','最新更新时间','比例尺分母','图幅等高距','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'1:5000',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/DiXingT/MapServer/2',
                str:"温州市大都市区范围，面积约3442.5 平方公里，共计图幅513幅。利用2004-2005年航摄影像资料，经2005年-2006年外业调绘后编制得到成果。",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','测区名称','测区代码','所有权单位名称','生产单位名称','密级','参照图式','大地基准','高程基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始测绘时间','更新时间','最新更新时间','比例尺分母','图幅等高距','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              }
            ]
          },
          {
            name:'影像',
            show:false,
            list:[
              {
                name:'1:5000（2005）',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/0',
                str:"2005年0.5米DOM，温州城市坐标系转温州2000坐标系",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'1:5000（2014）',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/1',
                str:"2014年温州三区0.5米DOM",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'1:2000（2012）',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/2',
                str:"2012年温州三区",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'2014年七都无人机影像',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/3',
                str:"2014年_无人机高分辨率影像动态更新数据成果 七都片区(0.2米)_温州2000坐标系",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'2014年温州市无人机影像',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/4',
                str:"2014年_无人机高分辨率影像动态更新数据成果 温州市区片区(0.2米)_温州2000坐标系",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'2015年仰义无人机影像',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/5',
                str:"2015年仰义片区0.2米无人机影像",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'2015年丽岙无人机影像',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/6',
                str:"2015年丽岙区0.2米无人机影像",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'2016年西片无人机影像',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/7',
                str:"2016年西片区0.2米无人机影像",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'2006年（2.5米分辨率）',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/8',
                str:"温州全市域",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'2008年（0.61米分辨率）',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/9',
                str:"苍南县、平阳县、泰顺县、文成县主城区范围，分辨率为0.61米，建库成果为真彩色。",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'2008年（1米分辨率）',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/10',
                str:"永嘉县、乐清市、瑞安市城区范围，分辨率为1米，建库成果为真彩色。",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'2008年（2.5米分辨率）',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/11',
                str:"温州全市域",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'2010年（0.5米分辨率）',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/12',
                str:"温州三区",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'2011年（0.5米分辨率）',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/13',
                str:"温州三区",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'2012年（2.5米分辨率）',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/14',
                str:"温州全市域",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:'2016年（2米分辨率）',
                url:'https://services.wzmap.gov.cn/server/rest/services/CEHUICG/YX/MapServer/15',
                str:"更新时间： 2016年",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','最新更新时间','比例尺分母','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'影像资料信息',
                    field:['摄区号','航摄比例尺分母','航摄焦距','航摄单位','航摄时间','影像分辨率','影像色彩']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
            ]
          },
          {
            name:'其他',
            show:false,
            list:[
              {
                name:"1:2000D(DLG1985年）",
                url:"https://services.wzmap.gov.cn/server/rest/services/CEHUICG/QiTa/MapServer/0",
                str:"更新时间：1985年",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['图号','图名','所在区','平面坐标系统','高程系统','比例尺','图式','成图方法','测制单位','测制时间','介质类型','成果类别','权属单位','资料保存单位','查询分发地','咨询电话']
                  }
                ]
              },
              {
                name:"1:2000D(DLG1988年）",
                url:"https://services.wzmap.gov.cn/server/rest/services/CEHUICG/QiTa/MapServer/1",
                str:"更新时间：1988年",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['图号','图名','所在区','平面坐标系统','高程系统','比例尺','图式','成图方法','测制单位','测制时间','介质类型','成果类别','权属单位','资料保存单位','查询分发地','咨询电话']
                  }
                ]
              },
              {
                name:"1:2000D(DLG1989年）",
                url:"https://services.wzmap.gov.cn/server/rest/services/CEHUICG/QiTa/MapServer/2",
                str:"更新时间：1989年",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['图号','图名','所在区','平面坐标系统','高程系统','比例尺','图式','成图方法','测制单位','测制时间','介质类型','成果类别','权属单位','资料保存单位','查询分发地','咨询电话']
                  }
                ]
              },
              {
                name:"1:2000D(DLG1992年）",
                url:"https://services.wzmap.gov.cn/server/rest/services/CEHUICG/QiTa/MapServer/3",
                str:"更新时间：1992年",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['图号','图名','所在区','平面坐标系统','高程系统','比例尺','图式','成图方法','测制单位','测制时间','介质类型','成果类别','权属单位','资料保存单位','查询分发地','咨询电话']
                  }
                ]
              },
              {
                name:"一等水准点",
                url:"https://services.wzmap.gov.cn/server/rest/services/CEHUICG/QiTa/MapServer/4",
                str:"经过历年复测，水准点（一期）包含一等点18个，二等点326个，三等点55个，合计399个。",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['控制点点号','控制点名称','控制点等级','成果类型','初测时间','复测时间','最新更新时间','所在地','所在图幅','点位详细说明','交通情况','概略经度','概略纬度','选点单位','选点时间','埋石单位','埋石时间','维修单位','维修日期','保管单位名称','保管人姓名','保管人联系电话']
                  }
                ]
              },
              {
                name:"二等水准点",
                url:"https://services.wzmap.gov.cn/server/rest/services/CEHUICG/QiTa/MapServer/5",
                str:"经过历年复测，水准点（一期）包含一等点18个，二等点326个，三等点55个，合计399个。",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['控制点点号','控制点名称','控制点等级','成果类型','初测时间','复测时间','最新更新时间','所在地','所在图幅','点位详细说明','交通情况','概略经度','概略纬度','选点单位','选点时间','埋石单位','埋石时间','维修单位','维修日期','保管单位名称','保管人姓名','保管人联系电话']
                  }
                ]
              },
              {
                name:"三等水准点",
                url:"https://services.wzmap.gov.cn/server/rest/services/CEHUICG/QiTa/MapServer/6",
                str:"经过历年复测，水准点（一期）包含一等点18个，二等点326个，三等点55个，合计399个。",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['控制点点号','控制点名称','控制点等级','成果类型','初测时间','复测时间','最新更新时间','所在地','所在图幅','点位详细说明','交通情况','概略经度','概略纬度','选点单位','选点时间','埋石单位','埋石时间','维修单位','维修日期','保管单位名称','保管人姓名','保管人联系电话']
                  }
                ]
              },
              {
                name:"二等GPS点",
                url:"https://services.wzmap.gov.cn/server/rest/services/CEHUICG/QiTa/MapServer/7",
                str:"GPS点包含二等点94个，三等点53个，四等点46个，合计193个，坐标系为温州2000坐标系。",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['控制点点号','控制点名称','控制点等级','成果类型','初测时间','复测时间','最新更新时间','所在地','所在图幅','点位详细说明','交通情况','概略经度','概略纬度','选点单位','选点时间','埋石单位','埋石时间','维修单位','维修日期','保管单位名称','保管人姓名','保管人联系电话']
                  }
                ]
              },
              {
                name:"三等GPS点",
                url:"https://services.wzmap.gov.cn/server/rest/services/CEHUICG/QiTa/MapServer/8",
                str:"GPS点包含二等点94个，三等点53个，四等点46个，合计193个，坐标系为温州2000坐标系。",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['控制点点号','控制点名称','控制点等级','成果类型','初测时间','复测时间','最新更新时间','所在地','所在图幅','点位详细说明','交通情况','概略经度','概略纬度','选点单位','选点时间','埋石单位','埋石时间','维修单位','维修日期','保管单位名称','保管人姓名','保管人联系电话']
                  }
                ]
              },
              {
                name:"四等GPS点",
                url:"https://services.wzmap.gov.cn/server/rest/services/CEHUICG/QiTa/MapServer/9",
                str:"GPS点包含二等点94个，三等点53个，四等点46个，合计193个，坐标系为温州2000坐标系。",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['控制点点号','控制点名称','控制点等级','成果类型','初测时间','复测时间','最新更新时间','所在地','所在图幅','点位详细说明','交通情况','概略经度','概略纬度','选点单位','选点时间','埋石单位','埋石时间','维修单位','维修日期','保管单位名称','保管人姓名','保管人联系电话']
                  }
                ]
              },
              {
                name:"1:5000DEM",
                url:"https://services.wzmap.gov.cn/server/rest/services/CEHUICG/QiTa/MapServer/10",
                str:"温州市大都市区范围，面积约3442.5平方公里，2005-2006年完成，基本等高距为5米。",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准','高程基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','更新时间','最新更新时间','比例尺分母','格网单元X方向尺寸','格网单元Y方向尺寸','格网排列方式','格网行列数','高程记录的小数点位数','起始格网单元左上角点X坐标','起始格网单元左上角点Y坐标','数据量','数据格式','图廓角点经度范围','图廓角点维度范围','行政区划']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:"1:2000DEM",
                url:"https://services.wzmap.gov.cn/server/rest/services/CEHUICG/QiTa/MapServer/11",
                str:"更新时间： 2014年",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','所有权单位名称','生产单位名称','密级','大地基准','高程基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始成图时间','更新时间','最新更新时间','比例尺分母','格网单元X方向尺寸','格网单元Y方向尺寸','格网排列方式','格网行列数','高程记录的小数点位数','起始格网单元左上角点X坐标','起始格网单元左上角点Y坐标','数据量','数据格式','图廓角点经度范围','图廓角点维度范围','行政区划']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:"精细城市三维模型数据",
                url:"https://services.wzmap.gov.cn/server/rest/services/CEHUICG/QiTa/MapServer/12",
                str:"2011年及2012年基于1:500地形图数据及高分辨影像数据，采用高精度三维建模及外业采集制作高清纹理的方法，完成温州市城区约40平方公里精细三维模型数据成果",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['制作时间','最新更新时间','制作面积','数据格式','坐标系统','高程基准','平面精度','高程精度','所有权单位']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:"2.5维仿真电子地图数据",
                url:"https://services.wzmap.gov.cn/server/rest/services/CEHUICG/QiTa/MapServer/13",
                str:"2010年及2011年制作完成温州市核心城区合计约200多平方公里范围的2.5维仿真电子地图数据。",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['制作时间','最新更新时间','制作面积','数据格式','坐标系统','平面精度','所有权单位']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              },
              {
                name:"地下管线数据",
                url:"https://services.wzmap.gov.cn/server/rest/services/CEHUICG/QiTa/MapServer/14",
                str:"数据覆盖温州市三区约238平方公里，2014年测制",
                tab:[
                  {
                    name:'产品基本信息',
                    field:['产品名称','测区名称','测区代码','所有权单位名称','生产单位名称','密级','参照图式','大地基准','高程基准']
                  },
                  {
                    name:'图幅基本信息',
                    field:['图幅号','图名','初始测绘时间','更新时间','最新更新时间','比例尺分母','图幅等高距','数据量','数据格式','图廓角点经度范围','图廓角点纬度范围','西边Y坐标','东边Y坐标','南边X坐标','北边X坐标','行政区划']
                  },
                  {
                    name:'分发单位信息',
                    field:['单位名称','联系电话','联系地址']
                  }
                ]
              }
            ]
          },
        ],
        content:{
          show:false,
          data:{}
        }
      }
    },
    computed:{
      contentData(){
        let data = [];
        for(let key in this.content.data){
          let val = this.content.data[key];
          if(!/^\w.*$/.test(key) && val){
            data.push({
              'key':key,
              'val':val
            })
          }
        }
        return data;
      }
    },
    methods:{
      mapload(map){
        const self = this;
      },
      dataShow(i){
        this.navData.forEach(function (item) {
          if(item.name!=i.name)
            item.show=false;
        });
        i.show=!i.show;
      },
      cehuiClick(graphic){
        console.log(JSON.stringify(graphic.attributes));
        this.content.show = true;
        this.content.data = graphic.attributes;
        this.tabidx = 0;
      },
      cehuiLoad(ii){
        const map = this.$refs.map.$data.map;
        if(map.findLayerById('cehui')!=null){
          map.remove(map.findLayerById('cehui'));
          if(ii.url==this.nowurl){
            this.nowurl = '';
            this.nowname = '';
            return;
          }
          return;
        }
        this.$vux.loading.show();
        const self = this;
        esriLoader.loadModules([
          'esri/tasks/support/Query',
          'esri/tasks/QueryTask',
          'esri/layers/FeatureLayer'
        ]).then(([Query,QueryTask,FeatureLayer])=>{
          let url = ii.url;
          self.nowurl = url;
          //self.nowtab = ii.tab;
          self.$set(self.$data,'nowtab',ii.tab);
          self.nowname = ii.name;
          self.nowstr = ii.str;
          let cehuiLayer = new FeatureLayer(url,{
            outFields: ["*"],
            id:'cehui',
            opacity:0.6
          });
          cehuiLayer.on('layerview-create',function () {
            self.$vux.loading.hide();
          })
          map.add(cehuiLayer);
        });
      }
    },
    mounted(){

    }
  }
</script>

<style lang="less">
  @import "cehui.less";
</style>
